import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import ReactQueryProvider from '@/providers/react-query';
import { Toaster } from 'sonner';
import ReduxProvider from '@/providers/react-redux';
import { SessionProvider } from 'next-auth/react';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const skelzl = localFont({
  src: '../fonts/Stolzl/stolzl_regular.otf',
  variable: '--font-skelzl',
  display: 'swap',
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${skelzl.className} antialiased max-w-[1730px] mx-auto`}
      >
        <SessionProvider refetchOnWindowFocus={false} refetchInterval={10 * 60}>
          <ReduxProvider>
            <ReactQueryProvider>
              {children}
              <Toaster />
            </ReactQueryProvider>
          </ReduxProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
